
// 888       888        d8888 8888888b.  888b    888 8888888 888b    888  .d8888b.   888 888 888
// 888   o   888       d88888 888   Y88b 8888b   888   888   8888b   888 d88P  Y88b  888 888 888
// 888  d8b  888      d88P888 888    888 88888b  888   888   88888b  888 888    888  888 888 888
// 888 d888b 888     d88P 888 888   d88P 888Y88b 888   888   888Y88b 888 888         888 888 888
// 888d88888b888    d88P  888 8888888P"  888 Y88b888   888   888 Y88b888 888  88888  888 888 888
// 88888P Y88888   d88P   888 888 T88b   888  Y88888   888   888  Y88888 888    888  Y8P Y8P Y8P
// 8888P   Y8888  d8888888888 888  T88b  888   Y8888   888   888   Y8888 Y88b  d88P   "   "   " 
// 888P     Y888 d88P     888 888   T88b 888    Y888 8888888 888    Y888  "Y8888P88  888 888 888
// 
// 
// This header file is generated by script.
// DON'T modify manually!
// Generate time: 2017/12/06 12:21:26

#include "../public_types/config.hpp"

#ifndef CONFIG_METHODS_HPP
#define CONFIG_METHODS_HPP 1

//  ====================
//  @file ./src/config/config.cc
//  ====================

//  source: ./src/config/config.cc:11
int Config_initGlobalConfig(GlobalConfig* mergeInto);

//  source: ./src/config/config.cc:30
int Config_mergeConfig(GlobalConfig* mergeTo, GlobalConfig* overwrite);

#endif

// md5sum:
// 07064801b5c59c658c91775f82eeebef  ./src/config/config.cc
