
// 888       888        d8888 8888888b.  888b    888 8888888 888b    888  .d8888b.   888 888 888
// 888   o   888       d88888 888   Y88b 8888b   888   888   8888b   888 d88P  Y88b  888 888 888
// 888  d8b  888      d88P888 888    888 88888b  888   888   88888b  888 888    888  888 888 888
// 888 d888b 888     d88P 888 888   d88P 888Y88b 888   888   888Y88b 888 888         888 888 888
// 888d88888b888    d88P  888 8888888P"  888 Y88b888   888   888 Y88b888 888  88888  888 888 888
// 88888P Y88888   d88P   888 888 T88b   888  Y88888   888   888  Y88888 888    888  Y8P Y8P Y8P
// 8888P   Y8888  d8888888888 888  T88b  888   Y8888   888   888   Y8888 Y88b  d88P   "   "   " 
// 888P     Y888 d88P     888 888   T88b 888    Y888 8888888 888    Y888  "Y8888P88  888 888 888
// 
// 
// This header file is generated by script.
// DON'T modify manually!
// Generate time: 2017/12/12 03:18:54

#include "../types/capture.hpp"
#include "../types/detect.hpp"
#include "../types/config.hpp"
#include "../types/api_error_no.hpp"
#include "../types/database_operation.hpp"

#ifndef API_API_HPP
#define API_API_HPP 1

#ifdef __cplusplus
extern "C" {
#endif

//  ====================
//  @file ./src/api/api.cc
//  ====================

//  source: ./src/api/api.cc:207
int face_detect(int frameId, int maxResultCapacity, API_OUT int* resultCount, API_OUT Detect_FaceInfoArray* results);

//  source: ./src/api/api.cc:234
int face_detect_one_face_in_last_frame(API_OUT_NON_NULL Detect_FaceInfo* result);

//  source: ./src/api/api.cc:218
int face_dispose_detect_results(int count, Detect_FaceInfoArray* results);

//  source: ./src/api/api.cc:144
int face_get_frame(const Capture_FrameRequestOpts* opts, API_OUT Capture_FrameImageInfo* resultInfo, API_OUT_NON_NULL ucharArray* resultData);

//  source: ./src/api/api.cc:111
int face_init(GlobalConfig* config);

//  source: ./src/api/api.cc:259
int face_ping_pong(int ping);

//  source: ./src/api/api.cc:106
void face_set_init_flag(int flag);

//  source: ./src/api/api.cc:246
int face_update(DB_Modification* modification);

#ifdef __cplusplus
}
#endif

#endif

// md5sum:
// 1376137fbf1e56648467a5b2d0e70164  ./src/api/api.cc
