
// 888       888        d8888 8888888b.  888b    888 8888888 888b    888  .d8888b.   888 888 888
// 888   o   888       d88888 888   Y88b 8888b   888   888   8888b   888 d88P  Y88b  888 888 888
// 888  d8b  888      d88P888 888    888 88888b  888   888   88888b  888 888    888  888 888 888
// 888 d888b 888     d88P 888 888   d88P 888Y88b 888   888   888Y88b 888 888         888 888 888
// 888d88888b888    d88P  888 8888888P"  888 Y88b888   888   888 Y88b888 888  88888  888 888 888
// 88888P Y88888   d88P   888 888 T88b   888  Y88888   888   888  Y88888 888    888  Y8P Y8P Y8P
// 8888P   Y8888  d8888888888 888  T88b  888   Y8888   888   888   Y8888 Y88b  d88P   "   "   " 
// 888P     Y888 d88P     888 888   T88b 888    Y888 8888888 888    Y888  "Y8888P88  888 888 888
// 
// 
// This header file is generated by script.
// DON'T modify manually!
// Generate time: 2017/12/15 19:57:19

#include "../types/capture.hpp"
#include "../types/detect.hpp"
#include "../types/config.hpp"
#include "../types/api_error_no.hpp"
#include "../types/database_operation.hpp"

#ifndef API_API_HPP
#define API_API_HPP 1

#ifdef __cplusplus
extern "C" {
#endif

//  ====================
//  @file ./src/api/api.cc
//  ====================

//  source: ./src/api/api.cc:178
int face_detect(int frameId, int maxResultCount, API_OUT int* _resultCount, API_OUT NEED_TO_FREE Detect_FaceInfoArray* _results);

//  source: ./src/api/api.cc:271
int face_detect1(API_OUT_NON_NULL Detect_FaceInfo* result, API_OUT Capture_FrameImageInfo* frameResult);

//  source: ./src/api/api.cc:256
int face_detect_one_face_in_last_frame(API_OUT_NON_NULL Detect_FaceInfo* result, API_OUT Capture_FrameImageInfo* frameResult);

//  source: ./src/api/api.cc:148
int face_draw_face_rect(int frameId, NON_NULL Detect_FaceRectAttr* attr, NON_NULL Detect_FaceInfo* faceInfo, API_OUT NEED_TO_FREE ucharArray* newImageData, API_OUT int* w, API_OUT int* h);

//  source: ./src/api/api.cc:93
int face_get_frame(API_OUT_NON_NULL Capture_FrameImageInfo* result);

//  source: ./src/api/api.cc:56
int face_init(GlobalConfig* config);

//  source: ./src/api/api.cc:322
int face_ping_pong(int ping);

//  source: ./src/api/api.cc:44
int face_set_debug_log(int apiGetFrameLog, int apiInvokeLog);

//  source: ./src/api/api.cc:39
void face_set_init_flag(int flag);

//  source: ./src/api/api.cc:280
int face_update(DB_Modification* m);

//  ====================
//  @file ./src/api/api_cowsay.cc
//  ====================

//  source: ./src/api/api_cowsay.cc:17
int cowSayDeprecatedAPI();

#ifdef __cplusplus
}
#endif

#endif

// md5sum:
// b9108c86501c76d045eb6985c35e1b57  ./src/api/api.cc
// f72835bfe5291a57250c1728d6d35e8f  ./src/api/api_cowsay.cc
