
// 888       888        d8888 8888888b.  888b    888 8888888 888b    888  .d8888b.   888 888 888
// 888   o   888       d88888 888   Y88b 8888b   888   888   8888b   888 d88P  Y88b  888 888 888
// 888  d8b  888      d88P888 888    888 88888b  888   888   88888b  888 888    888  888 888 888
// 888 d888b 888     d88P 888 888   d88P 888Y88b 888   888   888Y88b 888 888         888 888 888
// 888d88888b888    d88P  888 8888888P"  888 Y88b888   888   888 Y88b888 888  88888  888 888 888
// 88888P Y88888   d88P   888 888 T88b   888  Y88888   888   888  Y88888 888    888  Y8P Y8P Y8P
// 8888P   Y8888  d8888888888 888  T88b  888   Y8888   888   888   Y8888 Y88b  d88P   "   "   " 
// 888P     Y888 d88P     888 888   T88b 888    Y888 8888888 888    Y888  "Y8888P88  888 888 888
// 
// 
// This header file is generated by script.
// DON'T modify manually!
// Generate time: 2017/12/13 15:10:30

#include "./macro.hpp"

#ifndef TEST_UTILS_INDEX
#define TEST_UTILS_INDEX 1

//  ====================
//  @file ./test/utilities/index.cc
//  ====================

//  source: ./test/utilities/index.cc:21
int testCompareStrings(const char* s1, const char* s2);

//  source: ./test/utilities/index.cc:16
int testDone(const char* description);

//  source: ./test/utilities/index.cc:6
int testFailed(const char* description);

//  source: ./test/utilities/index.cc:11
int testPassed(const char* description);

#endif

// md5sum:
// dab471450b884e537500a50936904eec  ./test/utilities/index.cc
