#ifndef UTILS_OPENCV_HPP
#define UTILS_OPENCV_HPP 1

#define DEFAULT_LAPLACIAN_BLUR_THRESHOLD 90

typedef enum {
	COPY_RULE_BGR_TO_RGB = 1,
	COPY_RULE_KEEP_BGR = 2
} CopyBGRMat2ArrayRule;

#endif // UTILS_OPENCV_HPP
