
// 888       888        d8888 8888888b.  888b    888 8888888 888b    888  .d8888b.   888 888 888
// 888   o   888       d88888 888   Y88b 8888b   888   888   8888b   888 d88P  Y88b  888 888 888
// 888  d8b  888      d88P888 888    888 88888b  888   888   88888b  888 888    888  888 888 888
// 888 d888b 888     d88P 888 888   d88P 888Y88b 888   888   888Y88b 888 888         888 888 888
// 888d88888b888    d88P  888 8888888P"  888 Y88b888   888   888 Y88b888 888  88888  888 888 888
// 88888P Y88888   d88P   888 888 T88b   888  Y88888   888   888  Y88888 888    888  Y8P Y8P Y8P
// 8888P   Y8888  d8888888888 888  T88b  888   Y8888   888   888   Y8888 Y88b  d88P   "   "   " 
// 888P     Y888 d88P     888 888   T88b 888    Y888 8888888 888    Y888  "Y8888P88  888 888 888
// 
// 
// This header file is generated by script.
// DON'T modify manually!
// Generate time: 2017/12/04 06:49:07

#ifndef LOG_METHODS_HPP
#define LOG_METHODS_HPP 1

//  ====================
//  @file ./src/log/methods.cc
//  ====================

//  source: ./src/log/methods.cc:39
void Log_debug(const char* content);

//  source: ./src/log/methods.cc:118
void Log_dumpByteArray(char* array, int length, int maxLength, const char* name);

//  source: ./src/log/methods.cc:55
void Log_dumpFloat(float value, const char* name);

//  source: ./src/log/methods.cc:156
void Log_dumpFloatArray(float* array, int length, int maxLength, const char* name);

//  source: ./src/log/methods.cc:45
void Log_dumpInt(int value, const char* name);

//  source: ./src/log/methods.cc:81
void Log_dumpIntArray(int* array, int length, int maxLength, const char* name);

//  source: ./src/log/methods.cc:65
void Log_dumpString(const char* str, const char* name);

//  source: ./src/log/methods.cc:42
void Log_fatal(const char* content);

//  source: ./src/log/methods.cc:16
char* Log_getLogDatePrefix();

//  source: ./src/log/methods.cc:40
void Log_info(const char* content);

//  source: ./src/log/methods.cc:41
void Log_warn(const char* content);

#endif

// md5sum:
// 731e4383837e981de78e25db48d061eb  ./src/log/methods.cc
