#ifndef FIREFLY_FACEVERIFY_HPP_VERSION
#define FIREFLY_FACEVERIFY_HPP_VERSION 1

#define FF_FV_VERSION_MAJOR    3
#define FF_FV_VERSION_MINOR    0
#define FF_FV_VERSION_PATCH    1
#define FF_FV_VERSION (FF_FV_VERSION_MAJOR << 16 | FF_FV_VERSION_MINOR << 8 | FF_FV_VERSION_PATCH)

#define FF_FD_VERSION_MAJOR    3
#define FF_FD_VERSION_MINOR    0
#define FF_FD_VERSION_PATCH    0
#define FF_FD_VERSION (FF_FD_VERSION_MAJOR << 16 | FF_FD_VERSION_MINOR << 8 | FF_FD_VERSION_PATCH)

#define FF_GET_MAJOR_VERSION(__V) (__V&0x00ff0000)>>16
#define FF_GET_MINOR_VERSION(__V) (__V&0x0000ff00)>>8
#define FF_GET_PATCH_VERSION(__V) (__V&0x000000ff)

#define FF_STR_EXP(__A)			#__A
#define FF_STR(__A)				FF_STR_EXP(__A)
#define FF_FV_VERSION_STRING	FF_STR(FF_FV_VERSION_MAJOR) "." FF_STR(FF_FV_VERSION_MINOR) "." FF_STR(FF_FV_VERSION_PATCH)

#endif
