
// 888       888        d8888 8888888b.  888b    888 8888888 888b    888  .d8888b.   888 888 888
// 888   o   888       d88888 888   Y88b 8888b   888   888   8888b   888 d88P  Y88b  888 888 888
// 888  d8b  888      d88P888 888    888 88888b  888   888   88888b  888 888    888  888 888 888
// 888 d888b 888     d88P 888 888   d88P 888Y88b 888   888   888Y88b 888 888         888 888 888
// 888d88888b888    d88P  888 8888888P"  888 Y88b888   888   888 Y88b888 888  88888  888 888 888
// 88888P Y88888   d88P   888 888 T88b   888  Y88888   888   888  Y88888 888    888  Y8P Y8P Y8P
// 8888P   Y8888  d8888888888 888  T88b  888   Y8888   888   888   Y8888 Y88b  d88P   "   "   " 
// 888P     Y888 d88P     888 888   T88b 888    Y888 8888888 888    Y888  "Y8888P88  888 888 888
// 
// 
// This header file is generated by script.
// DON'T modify manually!
// Generate time: 2017/12/07 23:41:08

#include "opencv2/opencv.hpp"
#include "../types/base.hpp"
#include "../types/capture.hpp"

#ifndef MEDIA_HANDLERS_HPP
#define MEDIA_HANDLERS_HPP 1

//  ====================
//  @file ./src/media/capture.cc
//  ====================

//  source: ./src/media/capture.cc:105
int Capture_Init();

//  source: ./src/media/capture.cc:201
bool Capture_Read(cv::Mat* frame);

//  source: ./src/media/capture.cc:25
void Capture_enableUnitTest();

//  source: ./src/media/capture.cc:47
void physicalCaptureDeviceToString(char* result, PhysicalCaptureDevice* dev, bool markAsUse);

#endif

// md5sum:
// 4c096c10bc2faf31926cc302aead1295  ./src/media/capture.cc
